### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by jonybuzz** [jonybuzz/encontralo#8]
- Publicar anuncios random en cuentas de Facebook e Instagram
- Notificar una coincidencia entre perdidos y encontrados
- Tomar posts de páginas públicas de Facebook como entrada de anuncios
- Completar la info faltante de los posts de forma colaborativa. Útil en caso de creación automática de anuncios o para validar info ingresada por otros usuarios.

**Comment by flbaynac** [comment]
En mi opinión, si el proyecto va a ser de código abierto yo lo haría con tecnologias un poco más sencillas con el fin de atraer a más desarrolladores, por ejemplo el front con bootstrap y el backend con node o php. A su vez pensaría en como subsistiría la página, por ejemplo poner un sistema de recompensas que pueda pagar el que quiera encontrar a su mascota y que se le pague al que lo encuentre y que la página se quede con un porcentaje, o subsistir a base a anuncios o donaciones.

**Comment by jonybuzz** [comment]
Hola @flbaynac! Gracias por las sugerencias. El tema del mantenimiento y las tecnologías fue una de las decisiones más difíciles. Hay mucha variedad y gente para todo. Hice un balance entre estas cualidades:
- que estén entre las más usadas
- que sean modernas
- que sean fáciles de aprender y bien documentadas-
- y las que puedo dar soporte como admin del proyecto...

En cuanto al ingreso, va a ser gratuito para todos los usuarios :)

Si te interesa participar, sos más que bienvenido. Si sabés usar javascript, en el front hay algunas tareas bastante interesantes
